export type ElementCategory =
  | 'alkali-metal'
  | 'alkaline-earth'
  | 'transition-metal'
  | 'post-transition-metal'
  | 'metalloid'
  | 'reactive-nonmetal'
  | 'noble-gas'
  | 'lanthanide'
  | 'actinide'
  | 'unknown';

export type ElementBlock = 's' | 'p' | 'd' | 'f';
export type ElementState = 'solid' | 'liquid' | 'gas' | 'synthetic';

export interface ElementData {
  symbol: string;
  nameEn: string;
  nameBn: string;
  atomicNumber: number;
  atomicMass: number;
  period: number;
  group?: number;
  category?: ElementCategory;
  block?: ElementBlock;
  state?: ElementState;
  electronConfig?: string;
  electronegativity?: number; // Pauling scale
  atomicRadius?: number; // pm
  ionizationEnergy?: number; // kJ/mol
  latinName?: string;
  valency?: number[];
  isAufbauException?: boolean;
  gridRow?: number;
  gridCol?: number;
}

export const ELEMENTS: Record<string, ElementData> = {
  H: { symbol: 'H', nameEn: 'Hydrogen', nameBn: 'হাইড্রোজেন', atomicNumber: 1, atomicMass: 1.008, period: 1, group: 1, category: 'reactive-nonmetal', block: 's', state: 'gas', electronConfig: '1s¹', electronegativity: 2.2, atomicRadius: 53, ionizationEnergy: 1312, valency: [1], gridRow: 1, gridCol: 1 },
  He: { symbol: 'He', nameEn: 'Helium', nameBn: 'হিলিয়াম', atomicNumber: 2, atomicMass: 4.0026, period: 1, group: 18, category: 'noble-gas', block: 's', state: 'gas', electronConfig: '1s²', atomicRadius: 31, ionizationEnergy: 2372, valency: [0], gridRow: 1, gridCol: 18 },
  Li: { symbol: 'Li', nameEn: 'Lithium', nameBn: 'লিথিয়াম', atomicNumber: 3, atomicMass: 6.94, period: 2, group: 1, category: 'alkali-metal', block: 's', state: 'solid', electronConfig: '[He] 2s¹', electronegativity: 0.98, atomicRadius: 167, ionizationEnergy: 520, valency: [1], gridRow: 2, gridCol: 1 },
  Be: { symbol: 'Be', nameEn: 'Beryllium', nameBn: 'বেরিলিয়াম', atomicNumber: 4, atomicMass: 9.0122, period: 2, group: 2, category: 'alkaline-earth', block: 's', state: 'solid', electronConfig: '[He] 2s²', electronegativity: 1.57, atomicRadius: 112, ionizationEnergy: 899, valency: [2], gridRow: 2, gridCol: 2 },
  B: { symbol: 'B', nameEn: 'Boron', nameBn: 'বোরন', atomicNumber: 5, atomicMass: 10.81, period: 2, group: 13, category: 'metalloid', block: 'p', state: 'solid', electronConfig: '[He] 2s² 2p¹', electronegativity: 2.04, atomicRadius: 87, ionizationEnergy: 801, valency: [3], gridRow: 2, gridCol: 13 },
  C: { symbol: 'C', nameEn: 'Carbon', nameBn: 'কার্বন', atomicNumber: 6, atomicMass: 12.011, period: 2, group: 14, category: 'reactive-nonmetal', block: 'p', state: 'solid', electronConfig: '[He] 2s² 2p²', electronegativity: 2.55, atomicRadius: 67, ionizationEnergy: 1086, valency: [2, 4], gridRow: 2, gridCol: 14 },
  N: { symbol: 'N', nameEn: 'Nitrogen', nameBn: 'নাইট্রোজেন', atomicNumber: 7, atomicMass: 14.007, period: 2, group: 15, category: 'reactive-nonmetal', block: 'p', state: 'gas', electronConfig: '[He] 2s² 2p³', electronegativity: 3.04, atomicRadius: 56, ionizationEnergy: 1402, valency: [3, 5], gridRow: 2, gridCol: 15 },
  O: { symbol: 'O', nameEn: 'Oxygen', nameBn: 'অক্সিজেন', atomicNumber: 8, atomicMass: 15.999, period: 2, group: 16, category: 'reactive-nonmetal', block: 'p', state: 'gas', electronConfig: '[He] 2s² 2p⁴', electronegativity: 3.44, atomicRadius: 48, ionizationEnergy: 1314, valency: [2], gridRow: 2, gridCol: 16 },
  F: { symbol: 'F', nameEn: 'Fluorine', nameBn: 'ফ্লোরিন', atomicNumber: 9, atomicMass: 18.998, period: 2, group: 17, category: 'reactive-nonmetal', block: 'p', state: 'gas', electronConfig: '[He] 2s² 2p⁵', electronegativity: 3.98, atomicRadius: 42, ionizationEnergy: 1681, valency: [1], gridRow: 2, gridCol: 17 },
  Ne: { symbol: 'Ne', nameEn: 'Neon', nameBn: 'নিয়ন', atomicNumber: 10, atomicMass: 20.18, period: 2, group: 18, category: 'noble-gas', block: 'p', state: 'gas', electronConfig: '[He] 2s² 2p⁶', atomicRadius: 38, ionizationEnergy: 2081, valency: [0], gridRow: 2, gridCol: 18 },
  Na: { symbol: 'Na', nameEn: 'Sodium', nameBn: 'সোডিয়াম', atomicNumber: 11, atomicMass: 22.99, period: 3, group: 1, category: 'alkali-metal', block: 's', state: 'solid', electronConfig: '[Ne] 3s¹', electronegativity: 0.93, atomicRadius: 190, ionizationEnergy: 496, latinName: 'Natrium', valency: [1], gridRow: 3, gridCol: 1 },
  Mg: { symbol: 'Mg', nameEn: 'Magnesium', nameBn: 'ম্যাগনেসিয়াম', atomicNumber: 12, atomicMass: 24.305, period: 3, group: 2, category: 'alkaline-earth', block: 's', state: 'solid', electronConfig: '[Ne] 3s²', electronegativity: 1.31, atomicRadius: 145, ionizationEnergy: 738, valency: [2], gridRow: 3, gridCol: 2 },
  Al: { symbol: 'Al', nameEn: 'Aluminum', nameBn: 'অ্যালুমিনিয়াম', atomicNumber: 13, atomicMass: 26.982, period: 3, group: 13, category: 'post-transition-metal', block: 'p', state: 'solid', electronConfig: '[Ne] 3s² 3p¹', electronegativity: 1.61, atomicRadius: 118, ionizationEnergy: 578, valency: [3], gridRow: 3, gridCol: 13 },
  Si: { symbol: 'Si', nameEn: 'Silicon', nameBn: 'সিলিকন', atomicNumber: 14, atomicMass: 28.085, period: 3, group: 14, category: 'metalloid', block: 'p', state: 'solid', electronConfig: '[Ne] 3s² 3p²', electronegativity: 1.9, atomicRadius: 111, ionizationEnergy: 786, valency: [4], gridRow: 3, gridCol: 14 },
  P: { symbol: 'P', nameEn: 'Phosphorus', nameBn: 'ফসফরাস', atomicNumber: 15, atomicMass: 30.974, period: 3, group: 15, category: 'reactive-nonmetal', block: 'p', state: 'solid', electronConfig: '[Ne] 3s² 3p³', electronegativity: 2.19, atomicRadius: 98, ionizationEnergy: 1012, valency: [3, 5], gridRow: 3, gridCol: 15 },
  S: { symbol: 'S', nameEn: 'Sulfur', nameBn: 'সালফার (গন্ধক)', atomicNumber: 16, atomicMass: 32.06, period: 3, group: 16, category: 'reactive-nonmetal', block: 'p', state: 'solid', electronConfig: '[Ne] 3s² 3p⁴', electronegativity: 2.58, atomicRadius: 88, ionizationEnergy: 1000, valency: [2, 4, 6], gridRow: 3, gridCol: 16 },
  Cl: { symbol: 'Cl', nameEn: 'Chlorine', nameBn: 'ক্লোরিন', atomicNumber: 17, atomicMass: 35.45, period: 3, group: 17, category: 'reactive-nonmetal', block: 'p', state: 'gas', electronConfig: '[Ne] 3s² 3p⁵', electronegativity: 3.16, atomicRadius: 79, ionizationEnergy: 1251, valency: [1, 3, 5, 7], gridRow: 3, gridCol: 17 },
  Ar: { symbol: 'Ar', nameEn: 'Argon', nameBn: 'আর্গন', atomicNumber: 18, atomicMass: 39.948, period: 3, group: 18, category: 'noble-gas', block: 'p', state: 'gas', electronConfig: '[Ne] 3s² 3p⁶', atomicRadius: 71, ionizationEnergy: 1521, valency: [0], gridRow: 3, gridCol: 18 },
  K: { symbol: 'K', nameEn: 'Potassium', nameBn: 'পটাশিয়াম', atomicNumber: 19, atomicMass: 39.098, period: 4, group: 1, category: 'alkali-metal', block: 's', state: 'solid', electronConfig: '[Ar] 4s¹', electronegativity: 0.82, atomicRadius: 243, ionizationEnergy: 419, latinName: 'Kalium', valency: [1], gridRow: 4, gridCol: 1 },
  Ca: { symbol: 'Ca', nameEn: 'Calcium', nameBn: 'ক্যালসিয়াম', atomicNumber: 20, atomicMass: 40.078, period: 4, group: 2, category: 'alkaline-earth', block: 's', state: 'solid', electronConfig: '[Ar] 4s²', electronegativity: 1.0, atomicRadius: 194, ionizationEnergy: 590, valency: [2], gridRow: 4, gridCol: 2 },
  Sc: { symbol: 'Sc', nameEn: 'Scandium', nameBn: 'স্ক্যান্ডিয়াম', atomicNumber: 21, atomicMass: 44.956, period: 4, group: 3, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Ar] 3d¹ 4s²', electronegativity: 1.36, atomicRadius: 184, ionizationEnergy: 633, valency: [3], gridRow: 4, gridCol: 3 },
  Ti: { symbol: 'Ti', nameEn: 'Titanium', nameBn: 'টাইটানিয়াম', atomicNumber: 22, atomicMass: 47.867, period: 4, group: 4, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Ar] 3d² 4s²', electronegativity: 1.54, atomicRadius: 176, ionizationEnergy: 659, valency: [2, 3, 4], gridRow: 4, gridCol: 4 },
  V: { symbol: 'V', nameEn: 'Vanadium', nameBn: 'ভ্যানাডিয়াম', atomicNumber: 23, atomicMass: 50.942, period: 4, group: 5, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Ar] 3d³ 4s²', electronegativity: 1.63, atomicRadius: 171, ionizationEnergy: 651, valency: [2, 3, 4, 5], gridRow: 4, gridCol: 5 },
  Cr: { symbol: 'Cr', nameEn: 'Chromium', nameBn: 'ক্রোমিয়াম', atomicNumber: 24, atomicMass: 51.996, period: 4, group: 6, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Ar] 3d⁵ 4s¹', electronegativity: 1.66, atomicRadius: 166, ionizationEnergy: 653, valency: [2, 3, 6], isAufbauException: true, gridRow: 4, gridCol: 6 },
  Mn: { symbol: 'Mn', nameEn: 'Manganese', nameBn: 'ম্যাঙ্গানিজ', atomicNumber: 25, atomicMass: 54.938, period: 4, group: 7, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Ar] 3d⁵ 4s²', electronegativity: 1.55, atomicRadius: 161, ionizationEnergy: 717, valency: [2, 4, 7], gridRow: 4, gridCol: 7 },
  Fe: { symbol: 'Fe', nameEn: 'Iron', nameBn: 'লোহা (আয়রন)', atomicNumber: 26, atomicMass: 55.845, period: 4, group: 8, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Ar] 3d⁶ 4s²', electronegativity: 1.83, atomicRadius: 156, ionizationEnergy: 762, latinName: 'Ferrum', valency: [2, 3], gridRow: 4, gridCol: 8 },
  Co: { symbol: 'Co', nameEn: 'Cobalt', nameBn: 'কোবাল্ট', atomicNumber: 27, atomicMass: 58.933, period: 4, group: 9, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Ar] 3d⁷ 4s²', electronegativity: 1.88, atomicRadius: 152, ionizationEnergy: 760, valency: [2, 3], gridRow: 4, gridCol: 9 },
  Ni: { symbol: 'Ni', nameEn: 'Nickel', nameBn: 'নিকেল', atomicNumber: 28, atomicMass: 58.693, period: 4, group: 10, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Ar] 3d⁸ 4s²', electronegativity: 1.91, atomicRadius: 149, ionizationEnergy: 737, valency: [2, 3], gridRow: 4, gridCol: 10 },
  Cu: { symbol: 'Cu', nameEn: 'Copper', nameBn: 'তামা (কপার)', atomicNumber: 29, atomicMass: 63.546, period: 4, group: 11, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Ar] 3d¹⁰ 4s¹', electronegativity: 1.9, atomicRadius: 145, ionizationEnergy: 746, latinName: 'Cuprum', valency: [1, 2], isAufbauException: true, gridRow: 4, gridCol: 11 },
  Zn: { symbol: 'Zn', nameEn: 'Zinc', nameBn: 'দস্তা (জিঙ্ক)', atomicNumber: 30, atomicMass: 65.38, period: 4, group: 12, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Ar] 3d¹⁰ 4s²', electronegativity: 1.65, atomicRadius: 142, ionizationEnergy: 906, valency: [2], gridRow: 4, gridCol: 12 },
  Ga: { symbol: 'Ga', nameEn: 'Gallium', nameBn: 'গ্যালিয়াম', atomicNumber: 31, atomicMass: 69.723, period: 4, group: 13, category: 'post-transition-metal', block: 'p', state: 'solid', electronConfig: '[Ar] 3d¹⁰ 4s² 4p¹', electronegativity: 1.81, atomicRadius: 136, ionizationEnergy: 579, valency: [3], gridRow: 4, gridCol: 13 },
  Ge: { symbol: 'Ge', nameEn: 'Germanium', nameBn: 'জার্মেনিয়াম', atomicNumber: 32, atomicMass: 72.63, period: 4, group: 14, category: 'metalloid', block: 'p', state: 'solid', electronConfig: '[Ar] 3d¹⁰ 4s² 4p²', electronegativity: 2.01, atomicRadius: 125, ionizationEnergy: 762, valency: [2, 4], gridRow: 4, gridCol: 14 },
  As: { symbol: 'As', nameEn: 'Arsenic', nameBn: 'আর্সেনিক', atomicNumber: 33, atomicMass: 74.922, period: 4, group: 15, category: 'metalloid', block: 'p', state: 'solid', electronConfig: '[Ar] 3d¹⁰ 4s² 4p³', electronegativity: 2.18, atomicRadius: 114, ionizationEnergy: 947, valency: [3, 5], gridRow: 4, gridCol: 15 },
  Se: { symbol: 'Se', nameEn: 'Selenium', nameBn: 'সেলেনিয়াম', atomicNumber: 34, atomicMass: 78.971, period: 4, group: 16, category: 'reactive-nonmetal', block: 'p', state: 'solid', electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁴', electronegativity: 2.55, atomicRadius: 103, ionizationEnergy: 941, valency: [2, 4, 6], gridRow: 4, gridCol: 16 },
  Br: { symbol: 'Br', nameEn: 'Bromine', nameBn: 'ব্রোমিন', atomicNumber: 35, atomicMass: 79.904, period: 4, group: 17, category: 'reactive-nonmetal', block: 'p', state: 'liquid', electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁵', electronegativity: 2.96, atomicRadius: 94, ionizationEnergy: 1140, valency: [1, 3, 5], gridRow: 4, gridCol: 17 },
  Kr: { symbol: 'Kr', nameEn: 'Krypton', nameBn: 'ক্রিপ্টন', atomicNumber: 36, atomicMass: 83.798, period: 4, group: 18, category: 'noble-gas', block: 'p', state: 'gas', electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁶', electronegativity: 3.0, atomicRadius: 88, ionizationEnergy: 1351, valency: [0], gridRow: 4, gridCol: 18 },
  Rb: { symbol: 'Rb', nameEn: 'Rubidium', nameBn: 'রুবিডিয়াম', atomicNumber: 37, atomicMass: 85.468, period: 5, group: 1, category: 'alkali-metal', block: 's', state: 'solid', electronConfig: '[Kr] 5s¹', electronegativity: 0.82, atomicRadius: 265, ionizationEnergy: 403, valency: [1], gridRow: 5, gridCol: 1 },
  Sr: { symbol: 'Sr', nameEn: 'Strontium', nameBn: 'স্ট্রনশিয়াম', atomicNumber: 38, atomicMass: 87.62, period: 5, group: 2, category: 'alkaline-earth', block: 's', state: 'solid', electronConfig: '[Kr] 5s²', electronegativity: 0.95, atomicRadius: 219, ionizationEnergy: 550, valency: [2], gridRow: 5, gridCol: 2 },
  Y: { symbol: 'Y', nameEn: 'Yttrium', nameBn: 'ইট্রিয়াম', atomicNumber: 39, atomicMass: 88.906, period: 5, group: 3, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Kr] 4d¹ 5s²', electronegativity: 1.22, atomicRadius: 212, ionizationEnergy: 600, valency: [3], gridRow: 5, gridCol: 3 },
  Zr: { symbol: 'Zr', nameEn: 'Zirconium', nameBn: 'জিরকোনিয়াম', atomicNumber: 40, atomicMass: 91.224, period: 5, group: 4, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Kr] 4d² 5s²', electronegativity: 1.33, atomicRadius: 206, ionizationEnergy: 640, valency: [4], gridRow: 5, gridCol: 4 },
  Nb: { symbol: 'Nb', nameEn: 'Niobium', nameBn: 'নাইওবিয়াম', atomicNumber: 41, atomicMass: 92.906, period: 5, group: 5, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Kr] 4d⁴ 5s¹', electronegativity: 1.6, atomicRadius: 198, ionizationEnergy: 652, valency: [3, 5], isAufbauException: true, gridRow: 5, gridCol: 5 },
  Mo: { symbol: 'Mo', nameEn: 'Molybdenum', nameBn: 'মলিবডেনাম', atomicNumber: 42, atomicMass: 95.95, period: 5, group: 6, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Kr] 4d⁵ 5s¹', electronegativity: 2.16, atomicRadius: 190, ionizationEnergy: 684, valency: [2, 3, 4, 5, 6], isAufbauException: true, gridRow: 5, gridCol: 6 },
  Tc: { symbol: 'Tc', nameEn: 'Technetium', nameBn: 'টেকনেশিয়াম', atomicNumber: 43, atomicMass: 98, period: 5, group: 7, category: 'transition-metal', block: 'd', state: 'synthetic', electronConfig: '[Kr] 4d⁵ 5s²', electronegativity: 1.9, atomicRadius: 183, ionizationEnergy: 702, valency: [4, 7], gridRow: 5, gridCol: 7 },
  Ru: { symbol: 'Ru', nameEn: 'Ruthenium', nameBn: 'রুথেনিয়াম', atomicNumber: 44, atomicMass: 101.07, period: 5, group: 8, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Kr] 4d⁷ 5s¹', electronegativity: 2.2, atomicRadius: 178, ionizationEnergy: 710, valency: [2, 3, 4, 6, 8], isAufbauException: true, gridRow: 5, gridCol: 8 },
  Rh: { symbol: 'Rh', nameEn: 'Rhodium', nameBn: 'রোডিয়াম', atomicNumber: 45, atomicMass: 102.91, period: 5, group: 9, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Kr] 4d⁸ 5s¹', electronegativity: 2.28, atomicRadius: 173, ionizationEnergy: 720, valency: [2, 3, 4], isAufbauException: true, gridRow: 5, gridCol: 9 },
  Pd: { symbol: 'Pd', nameEn: 'Palladium', nameBn: 'প্যালাডিয়াম', atomicNumber: 46, atomicMass: 106.42, period: 5, group: 10, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Kr] 4d¹⁰', electronegativity: 2.2, atomicRadius: 169, ionizationEnergy: 804, valency: [2, 4], isAufbauException: true, gridRow: 5, gridCol: 10 },
  Ag: { symbol: 'Ag', nameEn: 'Silver', nameBn: 'রূপা (সিলভার)', atomicNumber: 47, atomicMass: 107.868, period: 5, group: 11, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Kr] 4d¹⁰ 5s¹', electronegativity: 1.93, atomicRadius: 165, ionizationEnergy: 731, latinName: 'Argentum', valency: [1], isAufbauException: true, gridRow: 5, gridCol: 11 },
  Cd: { symbol: 'Cd', nameEn: 'Cadmium', nameBn: 'ক্যাডমিয়াম', atomicNumber: 48, atomicMass: 112.414, period: 5, group: 12, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Kr] 4d¹⁰ 5s²', electronegativity: 1.69, atomicRadius: 161, ionizationEnergy: 868, valency: [2], gridRow: 5, gridCol: 12 },
  In: { symbol: 'In', nameEn: 'Indium', nameBn: 'ইন্ডিয়াম', atomicNumber: 49, atomicMass: 114.818, period: 5, group: 13, category: 'post-transition-metal', block: 'p', state: 'solid', electronConfig: '[Kr] 4d¹⁰ 5s² 5p¹', electronegativity: 1.78, atomicRadius: 156, ionizationEnergy: 558, valency: [3], gridRow: 5, gridCol: 13 },
  Sn: { symbol: 'Sn', nameEn: 'Tin', nameBn: 'টিন', atomicNumber: 50, atomicMass: 118.71, period: 5, group: 14, category: 'post-transition-metal', block: 'p', state: 'solid', electronConfig: '[Kr] 4d¹⁰ 5s² 5p²', electronegativity: 1.96, atomicRadius: 145, ionizationEnergy: 709, latinName: 'Stannum', valency: [2, 4], gridRow: 5, gridCol: 14 },
  Sb: { symbol: 'Sb', nameEn: 'Antimony', nameBn: 'অ্যান্টিমণি', atomicNumber: 51, atomicMass: 121.76, period: 5, group: 15, category: 'metalloid', block: 'p', state: 'solid', electronConfig: '[Kr] 4d¹⁰ 5s² 5p³', electronegativity: 2.05, atomicRadius: 133, ionizationEnergy: 834, latinName: 'Stibium', valency: [3, 5], gridRow: 5, gridCol: 15 },
  Te: { symbol: 'Te', nameEn: 'Tellurium', nameBn: 'টেলুরিয়াম', atomicNumber: 52, atomicMass: 127.6, period: 5, group: 16, category: 'metalloid', block: 'p', state: 'solid', electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁴', electronegativity: 2.1, atomicRadius: 123, ionizationEnergy: 869, valency: [2, 4, 6], gridRow: 5, gridCol: 16 },
  I: { symbol: 'I', nameEn: 'Iodine', nameBn: 'আয়োডিন', atomicNumber: 53, atomicMass: 126.904, period: 5, group: 17, category: 'reactive-nonmetal', block: 'p', state: 'solid', electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁵', electronegativity: 2.66, atomicRadius: 115, ionizationEnergy: 1008, valency: [1, 3, 5, 7], gridRow: 5, gridCol: 17 },
  Xe: { symbol: 'Xe', nameEn: 'Xenon', nameBn: 'জেনন', atomicNumber: 54, atomicMass: 131.293, period: 5, group: 18, category: 'noble-gas', block: 'p', state: 'gas', electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁶', electronegativity: 2.6, atomicRadius: 108, ionizationEnergy: 1170, valency: [0, 2, 4, 6], gridRow: 5, gridCol: 18 },
  Cs: { symbol: 'Cs', nameEn: 'Cesium', nameBn: 'সিজিয়াম', atomicNumber: 55, atomicMass: 132.905, period: 6, group: 1, category: 'alkali-metal', block: 's', state: 'solid', electronConfig: '[Xe] 6s¹', electronegativity: 0.79, atomicRadius: 298, ionizationEnergy: 376, valency: [1], gridRow: 6, gridCol: 1 },
  Ba: { symbol: 'Ba', nameEn: 'Barium', nameBn: 'বেরিয়াম', atomicNumber: 56, atomicMass: 137.327, period: 6, group: 2, category: 'alkaline-earth', block: 's', state: 'solid', electronConfig: '[Xe] 6s²', electronegativity: 0.89, atomicRadius: 248, ionizationEnergy: 503, valency: [2], gridRow: 6, gridCol: 2 },
  La: { symbol: 'La', nameEn: 'Lanthanum', nameBn: 'ল্যান্থানাম', atomicNumber: 57, atomicMass: 138.905, period: 6, group: 3, category: 'lanthanide', block: 'f', state: 'solid', electronConfig: '[Xe] 5d¹ 6s²', electronegativity: 1.1, atomicRadius: 226, ionizationEnergy: 538, valency: [3], gridRow: 9, gridCol: 4 },
  Ce: { symbol: 'Ce', nameEn: 'Cerium', nameBn: 'সিরিয়াম', atomicNumber: 58, atomicMass: 140.116, period: 6, category: 'lanthanide', block: 'f', state: 'solid', electronConfig: '[Xe] 4f¹ 5d¹ 6s²', electronegativity: 1.12, atomicRadius: 210, ionizationEnergy: 534, valency: [3, 4], gridRow: 9, gridCol: 5 },
  Pr: { symbol: 'Pr', nameEn: 'Praseodymium', nameBn: 'প্রাসিওডিমিয়াম', atomicNumber: 59, atomicMass: 140.908, period: 6, category: 'lanthanide', block: 'f', state: 'solid', electronConfig: '[Xe] 4f³ 6s²', electronegativity: 1.13, atomicRadius: 247, ionizationEnergy: 527, valency: [3, 4], gridRow: 9, gridCol: 6 },
  Nd: { symbol: 'Nd', nameEn: 'Neodymium', nameBn: 'নিওডিমিয়াম', atomicNumber: 60, atomicMass: 144.242, period: 6, category: 'lanthanide', block: 'f', state: 'solid', electronConfig: '[Xe] 4f⁴ 6s²', electronegativity: 1.14, atomicRadius: 206, ionizationEnergy: 533, valency: [3], gridRow: 9, gridCol: 7 },
  Pm: { symbol: 'Pm', nameEn: 'Promethium', nameBn: 'প্রমিথিয়াম', atomicNumber: 61, atomicMass: 145, period: 6, category: 'lanthanide', block: 'f', state: 'synthetic', electronConfig: '[Xe] 4f⁵ 6s²', electronegativity: 1.13, atomicRadius: 205, ionizationEnergy: 540, valency: [3], gridRow: 9, gridCol: 8 },
  Sm: { symbol: 'Sm', nameEn: 'Samarium', nameBn: 'সামারিয়াম', atomicNumber: 62, atomicMass: 150.36, period: 6, category: 'lanthanide', block: 'f', state: 'solid', electronConfig: '[Xe] 4f⁶ 6s²', electronegativity: 1.17, atomicRadius: 238, ionizationEnergy: 545, valency: [2, 3], gridRow: 9, gridCol: 9 },
  Eu: { symbol: 'Eu', nameEn: 'Europium', nameBn: 'ইউরোপিয়াম', atomicNumber: 63, atomicMass: 151.964, period: 6, category: 'lanthanide', block: 'f', state: 'solid', electronConfig: '[Xe] 4f⁷ 6s²', electronegativity: 1.2, atomicRadius: 231, ionizationEnergy: 547, valency: [2, 3], gridRow: 9, gridCol: 10 },
  Gd: { symbol: 'Gd', nameEn: 'Gadolinium', nameBn: 'গ্যাডোলিনিয়াম', atomicNumber: 64, atomicMass: 157.25, period: 6, category: 'lanthanide', block: 'f', state: 'solid', electronConfig: '[Xe] 4f⁷ 5d¹ 6s²', electronegativity: 1.2, atomicRadius: 233, ionizationEnergy: 593, valency: [3], gridRow: 9, gridCol: 11 },
  Tb: { symbol: 'Tb', nameEn: 'Terbium', nameBn: 'টারবিয়াম', atomicNumber: 65, atomicMass: 158.925, period: 6, category: 'lanthanide', block: 'f', state: 'solid', electronConfig: '[Xe] 4f⁹ 6s²', electronegativity: 1.2, atomicRadius: 225, ionizationEnergy: 566, valency: [3, 4], gridRow: 9, gridCol: 12 },
  Dy: { symbol: 'Dy', nameEn: 'Dysprosium', nameBn: 'ডিসপ্রোসিয়াম', atomicNumber: 66, atomicMass: 162.5, period: 6, category: 'lanthanide', block: 'f', state: 'solid', electronConfig: '[Xe] 4f¹⁰ 6s²', electronegativity: 1.22, atomicRadius: 228, ionizationEnergy: 573, valency: [3], gridRow: 9, gridCol: 13 },
  Ho: { symbol: 'Ho', nameEn: 'Holmium', nameBn: 'হোলমিয়াম', atomicNumber: 67, atomicMass: 164.93, period: 6, category: 'lanthanide', block: 'f', state: 'solid', electronConfig: '[Xe] 4f¹¹ 6s²', electronegativity: 1.23, atomicRadius: 226, ionizationEnergy: 581, valency: [3], gridRow: 9, gridCol: 14 },
  Er: { symbol: 'Er', nameEn: 'Erbium', nameBn: 'আরবিয়াম', atomicNumber: 68, atomicMass: 167.259, period: 6, category: 'lanthanide', block: 'f', state: 'solid', electronConfig: '[Xe] 4f¹² 6s²', electronegativity: 1.24, atomicRadius: 226, ionizationEnergy: 589, valency: [3], gridRow: 9, gridCol: 15 },
  Tm: { symbol: 'Tm', nameEn: 'Thulium', nameBn: 'থুলিয়াম', atomicNumber: 69, atomicMass: 168.934, period: 6, category: 'lanthanide', block: 'f', state: 'solid', electronConfig: '[Xe] 4f¹³ 6s²', electronegativity: 1.25, atomicRadius: 222, ionizationEnergy: 597, valency: [3], gridRow: 9, gridCol: 16 },
  Yb: { symbol: 'Yb', nameEn: 'Ytterbium', nameBn: 'ইটারবিয়াম', atomicNumber: 70, atomicMass: 173.045, period: 6, category: 'lanthanide', block: 'f', state: 'solid', electronConfig: '[Xe] 4f¹⁴ 6s²', electronegativity: 1.1, atomicRadius: 222, ionizationEnergy: 603, valency: [2, 3], gridRow: 9, gridCol: 17 },
  Lu: { symbol: 'Lu', nameEn: 'Lutetium', nameBn: 'লুটিশিয়াম', atomicNumber: 71, atomicMass: 174.967, period: 6, group: 3, category: 'lanthanide', block: 'd', state: 'solid', electronConfig: '[Xe] 4f¹⁴ 5d¹ 6s²', electronegativity: 1.27, atomicRadius: 217, ionizationEnergy: 524, valency: [3], gridRow: 9, gridCol: 18 },
  Hf: { symbol: 'Hf', nameEn: 'Hafnium', nameBn: 'হাফনিয়াম', atomicNumber: 72, atomicMass: 178.49, period: 6, group: 4, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Xe] 4f¹⁴ 5d² 6s²', electronegativity: 1.3, atomicRadius: 208, ionizationEnergy: 659, valency: [4], gridRow: 6, gridCol: 4 },
  Ta: { symbol: 'Ta', nameEn: 'Tantalum', nameBn: 'ট্যানটালাম', atomicNumber: 73, atomicMass: 180.948, period: 6, group: 5, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Xe] 4f¹⁴ 5d³ 6s²', electronegativity: 1.5, atomicRadius: 200, ionizationEnergy: 761, valency: [5], gridRow: 6, gridCol: 5 },
  W: { symbol: 'W', nameEn: 'Tungsten', nameBn: 'টাংস্টেন', atomicNumber: 74, atomicMass: 183.84, period: 6, group: 6, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Xe] 4f¹⁴ 5d⁴ 6s²', electronegativity: 2.36, atomicRadius: 193, ionizationEnergy: 770, latinName: 'Wolfram', valency: [2, 4, 6], gridRow: 6, gridCol: 6 },
  Re: { symbol: 'Re', nameEn: 'Rhenium', nameBn: 'রেনিয়াম', atomicNumber: 75, atomicMass: 186.207, period: 6, group: 7, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Xe] 4f¹⁴ 5d⁵ 6s²', electronegativity: 1.9, atomicRadius: 188, ionizationEnergy: 760, valency: [4, 6, 7], gridRow: 6, gridCol: 7 },
  Os: { symbol: 'Os', nameEn: 'Osmium', nameBn: 'অসমিয়াম', atomicNumber: 76, atomicMass: 190.23, period: 6, group: 8, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Xe] 4f¹⁴ 5d⁶ 6s²', electronegativity: 2.2, atomicRadius: 185, ionizationEnergy: 840, valency: [4, 6, 8], gridRow: 6, gridCol: 8 },
  Ir: { symbol: 'Ir', nameEn: 'Iridium', nameBn: 'ইরিডিয়াম', atomicNumber: 77, atomicMass: 192.217, period: 6, group: 9, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Xe] 4f¹⁴ 5d⁷ 6s²', electronegativity: 2.2, atomicRadius: 180, ionizationEnergy: 880, valency: [3, 4], gridRow: 6, gridCol: 9 },
  Pt: { symbol: 'Pt', nameEn: 'Platinum', nameBn: 'প্লাটিনাম', atomicNumber: 78, atomicMass: 195.084, period: 6, group: 10, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Xe] 4f¹⁴ 5d⁹ 6s¹', electronegativity: 2.28, atomicRadius: 177, ionizationEnergy: 870, valency: [2, 4], isAufbauException: true, gridRow: 6, gridCol: 10 },
  Au: { symbol: 'Au', nameEn: 'Gold', nameBn: 'স্বর্ণ (গোল্ড)', atomicNumber: 79, atomicMass: 196.967, period: 6, group: 11, category: 'transition-metal', block: 'd', state: 'solid', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹', electronegativity: 2.54, atomicRadius: 174, ionizationEnergy: 890, latinName: 'Aurum', valency: [1, 3], isAufbauException: true, gridRow: 6, gridCol: 11 },
  Hg: { symbol: 'Hg', nameEn: 'Mercury', nameBn: 'পারদ (মার্কারি)', atomicNumber: 80, atomicMass: 200.592, period: 6, group: 12, category: 'transition-metal', block: 'd', state: 'liquid', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s²', electronegativity: 2.0, atomicRadius: 171, ionizationEnergy: 1007, latinName: 'Hydrargyrum', valency: [1, 2], gridRow: 6, gridCol: 12 },
  Tl: { symbol: 'Tl', nameEn: 'Thallium', nameBn: 'থ্যালিয়াম', atomicNumber: 81, atomicMass: 204.38, period: 6, group: 13, category: 'post-transition-metal', block: 'p', state: 'solid', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹', electronegativity: 1.62, atomicRadius: 156, ionizationEnergy: 589, valency: [1, 3], gridRow: 6, gridCol: 13 },
  Pb: { symbol: 'Pb', nameEn: 'Lead', nameBn: 'সীসা (লেড)', atomicNumber: 82, atomicMass: 207.2, period: 6, group: 14, category: 'post-transition-metal', block: 'p', state: 'solid', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²', electronegativity: 2.33, atomicRadius: 154, ionizationEnergy: 716, latinName: 'Plumbum', valency: [2, 4], gridRow: 6, gridCol: 14 },
  Bi: { symbol: 'Bi', nameEn: 'Bismuth', nameBn: 'বিসমাথ', atomicNumber: 83, atomicMass: 208.98, period: 6, group: 15, category: 'post-transition-metal', block: 'p', state: 'solid', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³', electronegativity: 2.02, atomicRadius: 143, ionizationEnergy: 703, valency: [3, 5], gridRow: 6, gridCol: 15 },
  Po: { symbol: 'Po', nameEn: 'Polonium', nameBn: 'পোলোনিয়াম', atomicNumber: 84, atomicMass: 209, period: 6, group: 16, category: 'post-transition-metal', block: 'p', state: 'solid', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴', electronegativity: 2.0, atomicRadius: 135, ionizationEnergy: 812, valency: [2, 4], gridRow: 6, gridCol: 16 },
  At: { symbol: 'At', nameEn: 'Astatine', nameBn: 'অ্যাস্টাটিন', atomicNumber: 85, atomicMass: 210, period: 6, group: 17, category: 'metalloid', block: 'p', state: 'solid', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵', electronegativity: 2.2, atomicRadius: 127, ionizationEnergy: 920, valency: [1, 3, 5], gridRow: 6, gridCol: 17 },
  Rn: { symbol: 'Rn', nameEn: 'Radon', nameBn: 'রেডন', atomicNumber: 86, atomicMass: 222, period: 6, group: 18, category: 'noble-gas', block: 'p', state: 'gas', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶', atomicRadius: 120, ionizationEnergy: 1037, valency: [0], gridRow: 6, gridCol: 18 },
  Fr: { symbol: 'Fr', nameEn: 'Francium', nameBn: 'ফ্রান্সিয়াম', atomicNumber: 87, atomicMass: 223, period: 7, group: 1, category: 'alkali-metal', block: 's', state: 'solid', electronConfig: '[Rn] 7s¹', electronegativity: 0.7, atomicRadius: 348, ionizationEnergy: 380, valency: [1], gridRow: 7, gridCol: 1 },
  Ra: { symbol: 'Ra', nameEn: 'Radium', nameBn: 'রেডিয়াম', atomicNumber: 88, atomicMass: 226, period: 7, group: 2, category: 'alkaline-earth', block: 's', state: 'solid', electronConfig: '[Rn] 7s²', electronegativity: 0.9, atomicRadius: 283, ionizationEnergy: 509, valency: [2], gridRow: 7, gridCol: 2 },
  Ac: { symbol: 'Ac', nameEn: 'Actinium', nameBn: 'অ্যাক্টিনিয়াম', atomicNumber: 89, atomicMass: 227, period: 7, group: 3, category: 'actinide', block: 'f', state: 'solid', electronConfig: '[Rn] 6d¹ 7s²', electronegativity: 1.1, atomicRadius: 260, ionizationEnergy: 499, valency: [3], gridRow: 10, gridCol: 4 },
  Th: { symbol: 'Th', nameEn: 'Thorium', nameBn: 'থোরিয়াম', atomicNumber: 90, atomicMass: 232.038, period: 7, category: 'actinide', block: 'f', state: 'solid', electronConfig: '[Rn] 6d² 7s²', electronegativity: 1.3, atomicRadius: 237, ionizationEnergy: 587, valency: [4], gridRow: 10, gridCol: 5 },
  Pa: { symbol: 'Pa', nameEn: 'Protactinium', nameBn: 'প্রোট্যাক্টিনিয়াম', atomicNumber: 91, atomicMass: 231.036, period: 7, category: 'actinide', block: 'f', state: 'solid', electronConfig: '[Rn] 5f² 6d¹ 7s²', electronegativity: 1.5, atomicRadius: 243, ionizationEnergy: 568, valency: [4, 5], gridRow: 10, gridCol: 6 },
  U: { symbol: 'U', nameEn: 'Uranium', nameBn: 'ইউরেনিয়াম', atomicNumber: 92, atomicMass: 238.029, period: 7, category: 'actinide', block: 'f', state: 'solid', electronConfig: '[Rn] 5f³ 6d¹ 7s²', electronegativity: 1.38, atomicRadius: 240, ionizationEnergy: 598, valency: [3, 4, 5, 6], gridRow: 10, gridCol: 7 },
  Np: { symbol: 'Np', nameEn: 'Neptunium', nameBn: 'নেপচুনিয়াম', atomicNumber: 93, atomicMass: 237, period: 7, category: 'actinide', block: 'f', state: 'synthetic', electronConfig: '[Rn] 5f⁴ 6d¹ 7s²', electronegativity: 1.36, atomicRadius: 221, ionizationEnergy: 605, valency: [3, 4, 5, 6], gridRow: 10, gridCol: 8 },
  Pu: { symbol: 'Pu', nameEn: 'Plutonium', nameBn: 'প্লুটোনিয়াম', atomicNumber: 94, atomicMass: 244, period: 7, category: 'actinide', block: 'f', state: 'synthetic', electronConfig: '[Rn] 5f⁶ 7s²', electronegativity: 1.28, atomicRadius: 243, ionizationEnergy: 585, valency: [3, 4, 5, 6], gridRow: 10, gridCol: 9 },
  Am: { symbol: 'Am', nameEn: 'Americium', nameBn: 'আমেরিসিয়াম', atomicNumber: 95, atomicMass: 243, period: 7, category: 'actinide', block: 'f', state: 'synthetic', electronConfig: '[Rn] 5f⁷ 7s²', electronegativity: 1.13, atomicRadius: 244, ionizationEnergy: 578, valency: [3, 4, 5, 6], gridRow: 10, gridCol: 10 },
  Cm: { symbol: 'Cm', nameEn: 'Curium', nameBn: 'কুরিয়াম', atomicNumber: 96, atomicMass: 247, period: 7, category: 'actinide', block: 'f', state: 'synthetic', electronConfig: '[Rn] 5f⁷ 6d¹ 7s²', electronegativity: 1.28, atomicRadius: 245, ionizationEnergy: 581, valency: [3, 4], gridRow: 10, gridCol: 11 },
  Bk: { symbol: 'Bk', nameEn: 'Berkelium', nameBn: 'বার্কেলিয়াম', atomicNumber: 97, atomicMass: 247, period: 7, category: 'actinide', block: 'f', state: 'synthetic', electronConfig: '[Rn] 5f⁹ 7s²', electronegativity: 1.3, atomicRadius: 244, ionizationEnergy: 601, valency: [3, 4], gridRow: 10, gridCol: 12 },
  Cf: { symbol: 'Cf', nameEn: 'Californium', nameBn: 'ক্যালিফোর্নিয়াম', atomicNumber: 98, atomicMass: 251, period: 7, category: 'actinide', block: 'f', state: 'synthetic', electronConfig: '[Rn] 5f¹⁰ 7s²', electronegativity: 1.3, atomicRadius: 245, ionizationEnergy: 608, valency: [3], gridRow: 10, gridCol: 13 },
  Es: { symbol: 'Es', nameEn: 'Einsteinium', nameBn: 'আইনস্টাইনিয়াম', atomicNumber: 99, atomicMass: 252, period: 7, category: 'actinide', block: 'f', state: 'synthetic', electronConfig: '[Rn] 5f¹¹ 7s²', electronegativity: 1.3, atomicRadius: 245, ionizationEnergy: 619, valency: [3], gridRow: 10, gridCol: 14 },
  Fm: { symbol: 'Fm', nameEn: 'Fermium', nameBn: 'ফার্মিয়াম', atomicNumber: 100, atomicMass: 257, period: 7, category: 'actinide', block: 'f', state: 'synthetic', electronConfig: '[Rn] 5f¹² 7s²', electronegativity: 1.3, atomicRadius: 245, ionizationEnergy: 627, valency: [3], gridRow: 10, gridCol: 15 },
  Md: { symbol: 'Md', nameEn: 'Mendelevium', nameBn: 'মেন্ডেলিভিয়াম', atomicNumber: 101, atomicMass: 258, period: 7, category: 'actinide', block: 'f', state: 'synthetic', electronConfig: '[Rn] 5f¹³ 7s²', electronegativity: 1.3, atomicRadius: 246, ionizationEnergy: 635, valency: [2, 3], gridRow: 10, gridCol: 16 },
  No: { symbol: 'No', nameEn: 'Nobelium', nameBn: 'নোবেলিয়াম', atomicNumber: 102, atomicMass: 259, period: 7, category: 'actinide', block: 'f', state: 'synthetic', electronConfig: '[Rn] 5f¹⁴ 7s²', electronegativity: 1.3, atomicRadius: 246, ionizationEnergy: 642, valency: [2, 3], gridRow: 10, gridCol: 17 },
  Lr: { symbol: 'Lr', nameEn: 'Lawrencium', nameBn: 'লরেনসিয়াম', atomicNumber: 103, atomicMass: 266, period: 7, group: 3, category: 'actinide', block: 'd', state: 'synthetic', electronConfig: '[Rn] 5f¹⁴ 7s² 7p¹', electronegativity: 1.3, atomicRadius: 246, ionizationEnergy: 470, valency: [3], gridRow: 10, gridCol: 18 },
  Rf: { symbol: 'Rf', nameEn: 'Rutherfordium', nameBn: 'রাদারফোর্ডিয়াম', atomicNumber: 104, atomicMass: 267, period: 7, group: 4, category: 'transition-metal', block: 'd', state: 'synthetic', electronConfig: '[Rn] 5f¹⁴ 6d² 7s²', ionizationEnergy: 580, valency: [4], gridRow: 7, gridCol: 4 },
  Db: { symbol: 'Db', nameEn: 'Dubnium', nameBn: 'ডুবনিয়াম', atomicNumber: 105, atomicMass: 268, period: 7, group: 5, category: 'transition-metal', block: 'd', state: 'synthetic', electronConfig: '[Rn] 5f¹⁴ 6d³ 7s²', valency: [5], gridRow: 7, gridCol: 5 },
  Sg: { symbol: 'Sg', nameEn: 'Seaborgium', nameBn: 'সিবোরগিয়াম', atomicNumber: 106, atomicMass: 269, period: 7, group: 6, category: 'transition-metal', block: 'd', state: 'synthetic', electronConfig: '[Rn] 5f¹⁴ 6d⁴ 7s²', valency: [6], gridRow: 7, gridCol: 6 },
  Bh: { symbol: 'Bh', nameEn: 'Bohrium', nameBn: 'বোহরিয়াম', atomicNumber: 107, atomicMass: 270, period: 7, group: 7, category: 'transition-metal', block: 'd', state: 'synthetic', electronConfig: '[Rn] 5f¹⁴ 6d⁵ 7s²', valency: [7], gridRow: 7, gridCol: 7 },
  Hs: { symbol: 'Hs', nameEn: 'Hassium', nameBn: 'হাসিয়াম', atomicNumber: 108, atomicMass: 269, period: 7, group: 8, category: 'transition-metal', block: 'd', state: 'synthetic', electronConfig: '[Rn] 5f¹⁴ 6d⁶ 7s²', valency: [8], gridRow: 7, gridCol: 8 },
  Mt: { symbol: 'Mt', nameEn: 'Meitnerium', nameBn: 'মাইটনেরিয়াম', atomicNumber: 109, atomicMass: 278, period: 7, group: 9, category: 'transition-metal', block: 'd', state: 'synthetic', electronConfig: '[Rn] 5f¹⁴ 6d⁷ 7s²', gridRow: 7, gridCol: 9 },
  Ds: { symbol: 'Ds', nameEn: 'Darmstadtium', nameBn: 'ডার্মস্টাটিয়াম', atomicNumber: 110, atomicMass: 281, period: 7, group: 10, category: 'transition-metal', block: 'd', state: 'synthetic', electronConfig: '[Rn] 5f¹⁴ 6d⁸ 7s²', gridRow: 7, gridCol: 10 },
  Rg: { symbol: 'Rg', nameEn: 'Roentgenium', nameBn: 'রন্টজেনিয়াম', atomicNumber: 111, atomicMass: 282, period: 7, group: 11, category: 'transition-metal', block: 'd', state: 'synthetic', electronConfig: '[Rn] 5f¹⁴ 6d⁹ 7s²', gridRow: 7, gridCol: 11 },
  Cn: { symbol: 'Cn', nameEn: 'Copernicium', nameBn: 'কোপার্নিসিয়াম', atomicNumber: 112, atomicMass: 285, period: 7, group: 12, category: 'transition-metal', block: 'd', state: 'synthetic', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s²', valency: [2], gridRow: 7, gridCol: 12 },
  Nh: { symbol: 'Nh', nameEn: 'Nihonium', nameBn: 'নিহোনিয়াম', atomicNumber: 113, atomicMass: 286, period: 7, group: 13, category: 'post-transition-metal', block: 'p', state: 'synthetic', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹', gridRow: 7, gridCol: 13 },
  Fl: { symbol: 'Fl', nameEn: 'Flerovium', nameBn: 'ফ্লেরোভিয়াম', atomicNumber: 114, atomicMass: 289, period: 7, group: 14, category: 'post-transition-metal', block: 'p', state: 'synthetic', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²', gridRow: 7, gridCol: 14 },
  Mc: { symbol: 'Mc', nameEn: 'Moscovium', nameBn: 'মস্কোভিয়াম', atomicNumber: 115, atomicMass: 290, period: 7, group: 15, category: 'post-transition-metal', block: 'p', state: 'synthetic', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³', gridRow: 7, gridCol: 15 },
  Lv: { symbol: 'Lv', nameEn: 'Livermorium', nameBn: 'লিভারমোরিয়াম', atomicNumber: 116, atomicMass: 293, period: 7, group: 16, category: 'post-transition-metal', block: 'p', state: 'synthetic', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴', gridRow: 7, gridCol: 16 },
  Ts: { symbol: 'Ts', nameEn: 'Tennessine', nameBn: 'টেনেসিন', atomicNumber: 117, atomicMass: 294, period: 7, group: 17, category: 'reactive-nonmetal', block: 'p', state: 'synthetic', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵', gridRow: 7, gridCol: 17 },
  Og: { symbol: 'Og', nameEn: 'Oganesson', nameBn: 'ওগানেসন', atomicNumber: 118, atomicMass: 294, period: 7, group: 18, category: 'noble-gas', block: 'p', state: 'synthetic', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶', valency: [0], gridRow: 7, gridCol: 18 },
};

export const ELEMENT_LIST: ElementData[] = Object.values(ELEMENTS).sort((a, b) => a.atomicNumber - b.atomicNumber);

